exports.handler = async (event) => {
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, body: 'Method Not Allowed' };
  }

  const { email, itinerary, destination, departure, days, budget } = JSON.parse(event.body || '{}');

  if (!email || !itinerary) {
    return { statusCode: 400, body: JSON.stringify({ error: 'Missing email or itinerary.' }) };
  }

  const resendKey = process.env.RESEND_API_KEY;
  if (!resendKey) {
    return { statusCode: 500, body: JSON.stringify({ error: 'Email service not configured.' }) };
  }

  // Build a clean HTML email
  const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body { font-family: Georgia, serif; background: #f5f2ec; margin: 0; padding: 20px; color: #0f0e0c; }
    .wrapper { max-width: 600px; margin: 0 auto; background: #fff; border-radius: 12px; overflow: hidden; }
    .header { background: #1a6b4a; color: #fff; padding: 28px 32px; }
    .header h1 { font-size: 24px; margin: 0 0 6px; letter-spacing: -0.02em; }
    .header p { font-size: 14px; opacity: 0.85; margin: 0; }
    .body { padding: 28px 32px; }
    .trip-meta { display: flex; gap: 16px; background: #f5f2ec; border-radius: 10px; padding: 14px 18px; margin-bottom: 24px; font-size: 13px; }
    .meta-item { flex: 1; }
    .meta-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: #6b6760; margin-bottom: 3px; }
    .meta-value { font-weight: 600; color: #0f0e0c; }
    h2 { font-size: 18px; color: #1a6b4a; margin: 24px 0 10px; border-bottom: 1px solid #ece8df; padding-bottom: 8px; }
    p { font-size: 14px; line-height: 1.7; color: #3a3835; margin: 0 0 10px; }
    .footer { background: #f5f2ec; padding: 18px 32px; font-size: 12px; color: #b5b2ac; text-align: center; }
    pre { white-space: pre-wrap; font-family: Georgia, serif; font-size: 14px; line-height: 1.8; color: #3a3835; }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>Your TripMind Itinerary ✈️</h1>
      <p>${departure} → ${destination} · ${days} days · $${Number(budget).toLocaleString()} budget</p>
    </div>
    <div class="body">
      <pre>${itinerary.replace(/##\s*/g, '\n').replace(/\*\*/g, '')}</pre>
    </div>
    <div class="footer">
      Generated by TripMind · SEIS 666 Track B Project · Jay Zhu · Spring 2026
    </div>
  </div>
</body>
</html>`;

  try {
    const res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${resendKey}`
      },
      body: JSON.stringify({
        from: 'TripMind <onboarding@resend.dev>',
        to: [email],
        subject: `Your ${destination} Itinerary — TripMind`,
        html: emailHtml
      })
    });

    if (!res.ok) {
      const err = await res.json();
      throw new Error(err.message || 'Email send failed');
    }

    return { statusCode: 200, body: JSON.stringify({ success: true }) };
  } catch (err) {
    return { statusCode: 500, body: JSON.stringify({ error: err.message }) };
  }
};
